export const TYPE_META: Record<string, { label: string; color: string }> = {
  PERMINTAAN_HARGA: { label: "Permintaan Harga", color: "#9b59b6" },
  PENAWARAN: { label: "Penawaran", color: "#8e44ad" },
  MAP: { label: "MAP", color: "#2980b9" },
  SPK: { label: "SPK", color: "#16a085" },
  SO: { label: "SO", color: "#1abc9c" },
  PROOF: { label: "Proof Garmen", color: "#f39c12" },
  SJ_MEMO: { label: "SJ Memo", color: "#34495e" },
  MPPB: { label: "MPPB", color: "#0e6655" },
  MKB: { label: "MKB", color: "#e67e22" },
  PO: { label: "PO", color: "#d35400" },
  BPB: { label: "BPB", color: "#7f8c8d" },
  BPB_NON_BAHAN: { label: "BPB Non Bahan", color: "#95a5a6" },
  STBJ: { label: "STBJ", color: "#c0392b" },
  SJ: { label: "Surat Jalan", color: "#2c3e50" },
  INVOICE: { label: "Invoice", color: "#27ae60" },
  VOUCHER: { label: "Voucher", color: "#1565c0" },
  PLANNING_PPIC: { label: "Planning PPIC", color: "#8e44ad" },
  PERMINTAAN_BAHAN: { label: "Permintaan Bahan", color: "#d68910" },
  REALISASI_MINTA_BAHAN: { label: "Realisasi Minta Bahan", color: "#ca6f1e" },
  RETUR_LOG: { label: "Retur (Log)", color: "#a04000" },
  RETUR_BAHAN: { label: "Retur (Approved)", color: "#784212" },
  MKA: { label: "MKA", color: "#16a5a0" },
  PERMINTAAN_GARMEN: { label: "Permintaan Garmen", color: "#af601a" },
  REALISASI_GARMEN: { label: "Realisasi Garmen", color: "#935116" },
  PERMINTAAN_PEMBELIAN: { label: "Permintaan Pembelian", color: "#6c3483" },
  KASBON: { label: "Uang Muka", color: "#1e8449" },
  MUTASI_OUT: { label: "Mutasi Out", color: "#b9770e" },
  PO_NON_BAHAN: { label: "PO Non Bahan", color: "#a04000" },
  MUTASI_PRODUKSI: { label: "Mutasi Produksi", color: "#7d6608" },
  PO_JASA: { label: "PO Jasa", color: "#6e2c00" },
  BPJ: { label: "BPJ", color: "#873600" },
  PO_INTERNAL: { label: "PO Internal SPK", color: "#5b2c6f" },
  SJ_PO_INTERNAL: { label: "SJ PO Internal", color: "#4a235a" },
  JADWAL_KIRIM: { label: "Jadwal Kirim", color: "#117864" },
  SJ_TAK_NORMAL: { label: "SJ Tak Normal", color: "#1b2631" },
  INVOICE_TAK_NORMAL: { label: "Invoice Tak Normal", color: "#7b241c" },
  PENERIMAAN_PIUTANG: { label: "Penerimaan Piutang", color: "#1f618d" },
  PELUNASAN_PIUTANG: { label: "Pelunasan Piutang", color: "#154360" },
};
