// config/menuItems.ts
import { ref } from "vue";
import {
  IconSettings,
  IconFolder,
  IconLayoutList,
  IconShoppingCartDown,
  IconShirt,
  IconCashRegister,
  IconCreditCard,
  IconChartBar,
  IconSpeakerphone,
  IconBuildingWarehouse,
  IconTexture,
  IconPaperclip,
  IconTool,
  IconFlask,
  IconPuzzle,
  IconTruck,
  IconUsers,
  IconFileText,
  IconTruckDelivery,
  IconChecks,
  IconReceipt,
  IconListDetails,
  IconChartLine,
  IconNotes,
  IconBriefcase,
  IconFileInvoice,
  IconArrowBack,
  IconWeight,
  IconRuler,
  IconTag,
  IconPrinter,
  IconBarcode,
  IconShoppingCart,
  IconPackage,
  IconAlertCircle,
  IconFileDescription,
  IconShoppingCartCopy,
  IconReportAnalytics,
  IconFileAnalytics,
  IconClipboardText,
  IconCash,
  IconBuildingBank,
  IconScissors,
  IconShieldCheck,
  IconFileSpreadsheet,
  IconCurrencyDollar,
  IconLinkOff,
  IconFileAlert,
  IconClipboardList,
  IconClipboardX,
  IconTrendingUp,
  IconLayoutGrid,
  IconCoin,
  IconReportSearch,
  IconCalendarStats,
  IconBuildingFactory2,
  IconClipboardCheck,
  IconFileCheck,
  IconReceipt2,
  IconFileDots,
  IconTruckOff,
  IconReceiptTax,
  IconRuler2,
  IconArrowsExchange,
  IconScale,
  IconBoxSeam,
  IconClipboardData,
  IconGauge,
  IconListCheck,
  IconTruckLoading,
  IconCircleCheck,
  IconAlertTriangle,
  IconActivity,
  IconArrowBackUp,
  IconFileShredder,
  IconCalendarDue,
  IconClockHour4,
  IconTarget,
  IconFileDiff,
  IconHierarchy3,
  IconPhotoScan,
  IconPhotoSearch,
  IconMessageExclamation,
  IconDatabaseSearch,
  IconHourglass,
  IconShoppingBagPlus,
  IconCalendarCog,
  IconNotebook,
  IconCalendarWeek,
  IconTags,
  IconPhoto,
  IconFlag,
} from "@tabler/icons-vue";

export interface NavItem {
  title?: string;
  icon?: any;
  to?: string;
  divider?: boolean;
  onClick?: () => void;
  menuId?: number;
  items?: NavItem[];
  subItems?: NavItem[];
  model?: { value: boolean };
  adminOnly?: boolean;
}

// ⚠️ PENTING: array di bawah pakai `model: daftarMenu` dst yang tadinya
// ref() lokal di Navbar.vue. Karena file config ini sekarang di luar
// component scope, ref-ref itu dipindah jadi factory function supaya
// tiap kali Navbar.vue import, dia dapat instance ref baru (bukan
// singleton yang ke-share lintas komponen kalau suatu saat menuItems
// dipakai di >1 tempat).

export const createMenuItems = (): NavItem[] => {
  const daftarMenu = ref(false);
  const pembelianMenu = ref(false);
  const ppicMenu = ref(false);
  const garmenMenu = ref(false);
  const penjualanMenu = ref(false);
  const piutangMenu = ref(false);
  const laporanMenu = ref(false);
  const toolsMenu = ref(false);

  return [
    {
      title: "Daftar",
      icon: IconLayoutList,
      model: daftarMenu,
      menuId: 1,
      items: [
        {
          title: "Bahan",
          icon: IconTexture,
          menuId: 900,
          subItems: [
            {
              title: "Master Bahan",
              to: "/daftar/bahan/master",
              icon: IconListDetails,
              menuId: 11,
            },
            { divider: true },
            {
              title: "Jenis Bahan",
              to: "/daftar/bahan/jenis",
              icon: IconLayoutList,
              menuId: 25,
            },
            {
              title: "Warna Bahan",
              to: "/daftar/bahan/warna",
              icon: IconPaperclip,
              menuId: 26,
            },
            {
              title: "Gramasi",
              to: "/daftar/bahan/gramasi",
              icon: IconWeight,
              menuId: 27,
            },
            {
              title: "Setting",
              to: "/daftar/bahan/setting",
              icon: IconRuler,
              menuId: 28,
            },
          ],
        },
        {
          title: "Barang Garmen",
          to: "/daftar/barang-garmen",
          icon: IconShirt,
          menuId: 58,
        },
        {
          title: "Pengaturan Accesories",
          icon: IconPaperclip,
          menuId: 901,
          subItems: [
            {
              title: "Barang",
              to: "/daftar/accesories/barang",
              icon: IconPackage,
              menuId: 31,
            },
            {
              title: "Warna",
              to: "/daftar/accesories/warna",
              icon: IconPaperclip,
              menuId: 32,
            },
            {
              title: "Ukuran",
              to: "/daftar/accesories/ukuran",
              icon: IconRuler,
              menuId: 33,
            },
            {
              title: "Keterangan",
              to: "/daftar/accesories/keterangan",
              icon: IconTag,
              menuId: 34,
            },
          ],
        },
        {
          title: "Spare Part",
          to: "/daftar/sparepart",
          icon: IconTool,
          menuId: 35,
        },
        { title: "Obat", to: "/daftar/obat", icon: IconFlask, menuId: 24 },
        // {
        //   title: "Aset Perusahaan",
        //   to: "/daftar/aset-perusahaan",
        //   icon: IconBuildingBank,
        //   menuId: 38,
        // },
        {
          title: "Komponen",
          to: "/daftar/komponen",
          icon: IconPuzzle,
          menuId: 10,
        },
        {
          title: "Identitas Komp.",
          to: "/daftar/komponen-spk",
          icon: IconLayoutList,
          menuId: 18,
        },
        {
          title: "Standar Output",
          to: "/daftar/standart-output",
          icon: IconChartLine,
          menuId: 29,
        },
        {
          title: "Supplier",
          to: "/daftar/supplier",
          icon: IconTruck,
          menuId: 12,
        },
        { divider: true },
        {
          title: "Barang",
          to: "/daftar/barang",
          icon: IconPackage,
          menuId: 19,
        },
        {
          title: "Jenis Barang",
          to: "/daftar/jenis-barang",
          icon: IconLayoutList,
          menuId: 14,
        },
        {
          title: "Customer",
          to: "/daftar/customer",
          icon: IconUsers,
          menuId: 20,
        },
        {
          title: "Jenis Order",
          to: "/daftar/jenis-order",
          icon: IconLayoutList,
          menuId: 22,
        },
        {
          title: "Sales",
          to: "/daftar/sales",
          icon: IconBriefcase,
          menuId: 23,
        },
        { divider: true },
        {
          title: "BAP & Komplain",
          to: "/daftar/berita-acara",
          icon: IconAlertCircle,
          menuId: 142,
        },
        {
          title: "Complain Customer",
          to: "/daftar/complain-customer",
          icon: IconMessageExclamation,
          menuId: 36,
        },
        {
          title: "Kendala",
          to: "/daftar/kendala",
          icon: IconAlertTriangle,
          menuId: 37,
        },
      ],
    },
    {
      title: "Pembelian",
      icon: IconShoppingCartDown,
      model: pembelianMenu,
      menuId: 2,
      items: [
        {
          title: "Memo Kebutuhan Bahan (MKB)",
          to: "/pembelian/mkb",
          icon: IconFileText,
          menuId: 51,
        },
        {
          title: "PO Bahan",
          to: "/pembelian/po-bahan",
          icon: IconFileText,
          menuId: 52,
        },
        {
          title: "PO External Garmen",
          to: "/pembelian/po-external-garmen",
          icon: IconShoppingBagPlus,
          menuId: 144,
        },
        { divider: true },
        {
          title: "Setting Harga Bahan",
          icon: IconTags,
          subItems: [
            {
              title: "Garmen",
              to: "/pembelian/setting-harga-bahan/garmen",
              icon: IconShirt,
              menuId: 210,
            },
            {
              title: "MMT",
              to: "/pembelian/setting-harga-bahan/mmt",
              icon: IconPhoto,
              menuId: 211,
            },
            {
              title: "Spanduk",
              to: "/pembelian/setting-harga-bahan/spanduk",
              icon: IconFlag,
              menuId: 212,
            },
          ],
        },
      ],
    },
    {
      title: "PPIC",
      icon: IconClipboardText,
      model: ppicMenu,
      menuId: 9000,
      items: [
        {
          title: "Proof Garmen",
          to: "/ppic/proof",
          icon: IconClipboardCheck,
          menuId: 122,
        },
        {
          title: "Cetak BAST-MAP",
          to: "/garmen/cetak-bast",
          icon: IconPrinter,
          menuId: 117,
        },
        {
          title: "SPK (Surat Perintah Kerja)",
          to: "/ppic/spk",
          icon: IconClipboardText,
          menuId: 152,
        },
        {
          title: "Planning SPK PPIC",
          to: "/ppic/planning-spk",
          icon: IconCalendarStats,
          menuId: 56,
        },
        {
          title: "Komitmen Kirim",
          to: "/ppic/penjadwalan",
          icon: IconCalendarWeek,
          menuId: 176,
        },
        { divider: true },
        {
          title: "LHK Pola",
          to: "/garmen/lhk-pola",
          icon: IconRuler2,
          menuId: 174,
        },
      ],
    },
    {
      title: "Garmen",
      icon: IconShirt,
      model: garmenMenu,
      menuId: 3,
      items: [
        {
          title: "Bahan Baku",
          icon: IconTexture,
          menuId: 920,
          subItems: [
            {
              title: "Permintaan Bahan",
              to: "/garmen/bahan-baku/minta-bahan",
              icon: IconFileText,
              menuId: 127,
            },
            {
              title: "Retur Bahan",
              to: "/garmen/bahan-baku/retur-bahan",
              icon: IconArrowBack,
              menuId: 110,
            },
            { divider: true },
            {
              title: "Realisasi Permintaan",
              to: "/garmen/bahan-baku/realisasi-minta",
              icon: IconChecks,
              menuId: 108,
            },
            {
              title: "Approve Retur",
              to: "/garmen/bahan-baku/approve-retur",
              icon: IconChecks,
              menuId: 137,
            },
            {
              title: "Koreksi Stok",
              to: "/garmen/bahan-baku/koreksi-stok",
              icon: IconSettings,
              menuId: 115,
            },
            { divider: true },
            {
              title: "BPB",
              to: "/garmen/bahan-baku/bpb-bahan",
              icon: IconTruckDelivery,
              menuId: 101,
            },
            {
              title: "Retur Pembelian Bahan",
              to: "/garmen/bahan-baku/retur-pembelian-bahan",
              icon: IconArrowBackUp,
              menuId: 55,
            },
            { divider: true },
            {
              title: "Pembuatan Barcode Bahan",
              to: "/garmen/bahan-baku/pembuatan-barcode-bahan",
              icon: IconBarcode,
              menuId: 135,
            },
            {
              title: "Cetak Barcode",
              to: "/garmen/bahan/cetak-barcode",
              icon: IconPrinter,
              menuId: 112,
            },
          ],
        },
        {
          title: "Bahan Jadi",
          icon: IconShirt,
          menuId: 921,
          subItems: [
            {
              title: "Cetak Barcode Kaosan",
              to: "/garmen/bahan-jadi/cetak-barcode-kaosan",
              icon: IconBarcode,
              menuId: 130,
            },
            {
              title: "Surat Terima Barang Jadi (STBJ)",
              to: "/garmen/bahan-jadi/stbj",
              icon: IconClipboardCheck,
              menuId: 105,
            },
            {
              title: "Cetak Bukti Keluar Barang Jadi (BKBJ)",
              to: "/garmen/bahan-jadi/cetak-bkbj",
              icon: IconFileInvoice,
              menuId: 143,
            },
            {
              title: "Koreksi Stok Barang Jadi",
              to: "/garmen/bahan-jadi/koreksi-stok",
              icon: IconSettings,
              menuId: 114,
            },
          ],
        },
        {
          title: "MKA (Memo Kebutuhan Accesories)",
          to: "/garmen/mka",
          icon: IconNotes,
          menuId: 57,
        },
        {
          title: "Barang",
          icon: IconPackage,
          menuId: 59,
          subItems: [
            {
              title: "Permintaan Barang",
              to: "/garmen/barang/permintaan",
              icon: IconFileText,
              menuId: 60,
            },
            {
              title: "Realisasi Permintaan",
              to: "/garmen/barang/realisasi",
              icon: IconChecks,
              menuId: 62,
            },
            {
              title: "Retur Barang",
              to: "/garmen/barang/retur-barang",
              icon: IconArrowBack,
              menuId: 61,
            },
            {
              title: "Approve Retur",
              to: "/garmen/barang/approve-retur-barang",
              icon: IconChecks,
              menuId: 63,
            },
            {
              title: "Koreksi Stok",
              to: "/garmen/barang/koreksi-stok",
              icon: IconSettings,
              menuId: 64,
            },
            {
              title: "Minta Pembelian",
              to: "/garmen/barang/permintaan-pembelian",
              icon: IconShoppingCart,
              menuId: 65,
            },
            {
              title: "Mutasi In",
              to: "/garmen/barang/mutasi-in",
              icon: IconTruckDelivery,
              menuId: 69,
            },
            {
              title: "Mutasi Out",
              to: "/garmen/barang/mutasi-out",
              icon: IconTruckDelivery,
              menuId: 70,
            },
            {
              title: "PO Non Bahan",
              to: "/garmen/barang/po-nonbahan",
              icon: IconFileInvoice,
              menuId: 66,
            },
            {
              title: "BPB Non Bahan",
              to: "/garmen/barang/bpb-nonbahan",
              icon: IconPackage,
              menuId: 67,
            },
            {
              title: "Retur Pembelian",
              to: "/garmen/barang/retur-pembelian",
              icon: IconTruckOff,
              menuId: 68,
            },
          ],
        },
        {
          title: "SPK Gudang",
          to: "/garmen/spk-gudang",
          icon: IconClipboardList,
          menuId: 79,
        },
        { divider: true },
        {
          title: "PO Jasa",
          to: "/garmen/po-jasa",
          icon: IconClipboardList,
          menuId: 102,
        },
        {
          title: "Approve PO Jasa",
          to: "/garmen/approve-po-jasa",
          icon: IconClipboardCheck,
          menuId: 113,
        },
        {
          title: "Bukti Penerimaan Jasa (BPB Jasa)",
          to: "/garmen/bpb-jasa",
          icon: IconFileCheck,
          menuId: 104,
        },
        { divider: true },
        {
          title: "PO Internal MAP",
          icon: IconFileShredder,
          menuId: 925,
          subItems: [
            {
              title: "Daftar PO Internal MAP",
              to: "/garmen/po-internal-map",
              icon: IconListDetails,
              menuId: 138,
            },
            {
              title: "Surat Jalan MAP",
              to: "/garmen/po-internal-map/surat-jalan",
              icon: IconTruckDelivery,
              menuId: 139,
            },
            {
              title: "Approval Surat Jalan",
              to: "/garmen/po-internal-map/approve",
              icon: IconChecks,
              menuId: 140,
            },
          ],
        },
        {
          title: "PO Internal SPK",
          icon: IconFileInvoice,
          menuId: 926,
          subItems: [
            {
              title: "PO Internal",
              to: "/garmen/po-internal-spk/po-internal",
              icon: IconListDetails,
              menuId: 124,
            },
            {
              title: "Surat Jalan PO Internal",
              to: "/garmen/po-internal-spk/sj-po-internal",
              icon: IconTruckDelivery,
              menuId: 125,
            },
            {
              title: "Approval Surat Jalan PO Internal",
              to: "/garmen/po-internal-spk/approve-sj",
              icon: IconCircleCheck,
              menuId: 126,
            },
          ],
        },
        {
          title: "Planning per SPK",
          icon: IconCalendarStats,
          menuId: 927,
          subItems: [
            {
              title: "Input Planning",
              to: "/garmen/planning-per-spk/input-planning",
              icon: IconCalendarStats,
              menuId: 80,
            },
            {
              title: "Planning per Tanggal",
              to: "/garmen/planning-per-spk/planning-per-tgl",
              icon: IconCalendarDue,
              menuId: 81,
            },
            {
              title: "Planning SPK vs Realisasi",
              to: "/garmen/planning-per-spk/plan-vs-realisasi",
              icon: IconChartBar,
              menuId: 82,
            },
          ],
        },
        { divider: true },
        {
          title: "Mutasi Produksi",
          to: "/garmen/mutasi-produksi",
          icon: IconBuildingFactory2,
          menuId: 109,
        },
        { divider: true },
        {
          title: "Pemakaian Obat",
          to: "/garmen/pemakaian-obat",
          icon: IconFlask,
          menuId: 120,
        },
        {
          title: "DTF/DTG",
          icon: IconPhotoSearch,
          menuId: 928,
          subItems: [
            {
              title: "SO DTF/DTG",
              to: "/garmen/dtf/so-dtf",
              icon: IconPhotoSearch,
              menuId: 128,
            },
            {
              title: "LHK SO DTF/DTG",
              to: "/garmen/dtf/lhk-so-dtf",
              icon: IconClipboardList,
              menuId: 123,
            },
          ],
        },
        {
          title: "PO Paperprint",
          to: "/garmen/po-paperprint",
          icon: IconFileText,
          menuId: 103,
        },
        {
          title: "PO DTF",
          to: "/garmen/po-dtf",
          icon: IconPhotoScan,
          menuId: 141,
        },
      ],
    },
    {
      title: "Penjualan",
      icon: IconCashRegister,
      model: penjualanMenu,
      menuId: 6,
      items: [
        {
          title: "MPPB",
          to: "/penjualan/mppb",
          icon: IconFileDescription,
          menuId: 150,
        },
        {
          title: "Pra Order",
          to: "/penjualan/pra-order",
          icon: IconNotebook,
          menuId: 175,
        },
        {
          title: "Permintaan Harga",
          to: "/penjualan/minta-harga",
          icon: IconReceipt,
          menuId: 166,
        },
        {
          title: "Penawaran",
          to: "/penjualan/penawaran",
          icon: IconFileText,
          menuId: 151,
        },
        {
          title: "Sales Order",
          to: "/penjualan/sales-order",
          icon: IconShoppingCartCopy,
          menuId: 172,
        },
        { divider: true },
        {
          title: "Pra Surat Jalan",
          to: "/penjualan/pra-sj",
          icon: IconFileDots,
          menuId: 168,
        },
        {
          title: "Surat Jalan",
          to: "/penjualan/surat-jalan",
          icon: IconTruck,
          menuId: 153,
        },
        {
          title: "Surat Jalan Tak Normal",
          to: "/penjualan/sj-tak-normal",
          icon: IconTruckOff,
          menuId: 154,
        },
        {
          title: "Update Status Surat Jalan",
          to: "/penjualan/update-status-sj",
          icon: IconTruckDelivery,
          menuId: 155,
        },
        {
          title: "Approval Surat Jalan",
          to: "/penjualan/approval-sj",
          icon: IconClipboardCheck,
          menuId: 165,
        },
        { divider: true },
        {
          title: "Invoice",
          to: "/penjualan/invoice",
          icon: IconReceipt,
          menuId: 156,
        },
        {
          title: "Invoice Proforma",
          to: "/penjualan/invoice-proforma",
          icon: IconFileInvoice,
          menuId: 157,
        },
        {
          title: "Invoice Tak Normal",
          to: "/penjualan/invoice-tak-normal",
          icon: IconReceipt2,
          menuId: 158,
        },
        {
          title: "Cetak Kuitansi",
          to: "/penjualan/cetak-kuitansi",
          icon: IconReceipt2,
          menuId: 1317,
        },
        {
          title: "Cetak Faktur Pajak",
          to: "/penjualan/cetak-faktur-pajak",
          icon: IconReceiptTax,
          menuId: 159,
        },
        {
          title: "Export CSV ke Faktur Pajak",
          to: "/penjualan/export-csv-pajak",
          icon: IconFileSpreadsheet,
          menuId: 160,
        },
        { divider: true },
        {
          title: "MAP (Memo Approval Produk)",
          to: "/penjualan/map",
          icon: IconFileInvoice,
          menuId: 162,
        },
        {
          title: "Surat Jalan MAP",
          to: "/penjualan/sj-map",
          icon: IconTruckDelivery,
          menuId: 163,
        },
        {
          title: "Update Status SJ Memo",
          to: "/penjualan/update-sj-map",
          icon: IconChecks,
          menuId: 164,
        },
        {
          title: "Insentif",
          to: "/penjualan/insentif",
          icon: IconCoin,
          menuId: 167,
        },
        { divider: true },
        {
          title: "Jadwal Kirim",
          to: "/penjualan/jadwal-kirim",
          icon: IconTruckDelivery,
          menuId: 119,
        },
      ],
    },
    {
      title: "Piutang",
      icon: IconCreditCard,
      model: piutangMenu,
      menuId: 8,
      items: [
        {
          title: "Penerimaan",
          icon: IconLayoutList,
          menuId: 950,
          subItems: [
            {
              title: "Giro",
              to: "/piutang/penerimaan/giro",
              icon: IconCreditCard,
              menuId: 251,
            },
            {
              title: "Cash",
              to: "/piutang/penerimaan/cash",
              icon: IconCash,
              menuId: 252,
            },
            {
              title: "Transfer",
              to: "/piutang/penerimaan/transfer",
              icon: IconBuildingBank,
              menuId: 253,
            },
            {
              title: "Potongan",
              to: "/piutang/penerimaan/potongan",
              icon: IconScissors,
              menuId: 254,
            },
          ],
        },
        {
          title: "Pelunasan",
          to: "/piutang/pelunasan",
          icon: IconCoin,
          menuId: 255,
        },
        {
          title: "Pengajuan Dana",
          to: "/piutang/pengajuan-dana",
          icon: IconCash,
          menuId: 177,
        },
      ],
    },
    {
      title: "Laporan",
      icon: IconChartBar,
      model: laporanMenu,
      menuId: 9,
      items: [
        {
          title: "Laporan Gudang Garmen",
          icon: IconBuildingWarehouse,
          menuId: 960,
          subItems: [
            {
              title: "Stok Bahan Barcode",
              to: "/laporan/gudang-garmen/stok-bahan-barcode",
              icon: IconFileDescription,
              menuId: 501,
            },
            {
              title: "Kartu Stok Bahan",
              to: "/laporan/gudang-garmen/kartu-stok-bahan",
              icon: IconClipboardList,
              menuId: 502,
            },
            {
              title: "Kartu Stok Barang",
              to: "/laporan/gudang-garmen/kartu-stok-barang",
              icon: IconFileSpreadsheet,
              menuId: 503,
            },
            {
              title: "Mutasi Stok Bahan",
              to: "/laporan/gudang-garmen/mutasi-stok-bahan",
              icon: IconArrowsExchange,
              menuId: 505,
            },
            {
              title: "Stok Accesories vs MKA",
              to: "/laporan/gudang-garmen/stok-acc-vs-mka",
              icon: IconScale,
              menuId: 569,
            },
            {
              title: "Stok Gudang DC",
              to: "/laporan/gudang-garmen/stok-dc",
              icon: IconBuildingWarehouse,
              menuId: 570,
            },
            { divider: true },
            {
              title: "Stok Barang Jadi",
              to: "/laporan/gudang-garmen/stok-barang-jadi",
              icon: IconBoxSeam,
              menuId: 506,
            },
            {
              title: "Kartu Stok Barang Jadi",
              to: "/laporan/gudang-garmen/kartu-stok-barangjadi",
              icon: IconClipboardData,
              menuId: 507,
            },
            {
              title: "Mutasi Stok Barang Jadi",
              to: "/laporan/gudang-garmen/mutasi-stok-barang-jadi",
              icon: IconArrowsExchange,
              menuId: 508,
            },
            {
              title: "Realisasi Keluar Bahan",
              to: "/laporan/gudang-garmen/realisasi-keluar-bahan",
              icon: IconClipboardCheck,
              menuId: 529,
            },
            {
              title: "Umur Stok Bahan",
              to: "/laporan/gudang-garmen/umur-stok-bahan",
              icon: IconHourglass,
              menuId: 530,
            },
            { divider: true },
            {
              title: "Standart Babaran vs Realisasi",
              to: "/laporan/gudang-garmen/standart-babaran-vs-realisasi",
              icon: IconScale,
              menuId: 509,
            },
            {
              title: "SO Belum Ada MKB",
              to: "/laporan/gudang-garmen/spk-belum-mkb",
              icon: IconFileAlert,
              menuId: 510,
            },
            {
              title: "PO Bahan vs MKB",
              to: "/laporan/gudang-garmen/po-bahan-vs-mkb",
              icon: IconFileAnalytics,
              menuId: 511,
            },
            {
              title: "PO Bahan vs BPB",
              to: "/laporan/gudang-garmen/po-bahan-vs-bpb",
              icon: IconTruckDelivery,
              menuId: 512,
            },
            {
              title: "PO Jasa vs BPB Jasa",
              to: "/laporan/gudang-garmen/poj-vs-bpj",
              icon: IconFileInvoice,
              menuId: 513,
            },
            {
              title: "Outstanding PO Mitra",
              to: "/laporan/gudang-garmen/outstanding-po-mitra",
              icon: IconGauge,
              menuId: 514,
            },
            {
              title: "Realisasi Minta Bahan",
              to: "/laporan/gudang-garmen/realisasi-minta-bahan",
              icon: IconClipboardList,
              menuId: 515,
            },
            {
              title: "Realisasi Minta Bahan vs LHK Cutting",
              to: "/laporan/gudang-garmen/realisasi-minta-vs-lhk-cutt",
              icon: IconClipboardCheck,
              menuId: 568,
            },
            {
              title: "SPK DTF Belum PO DTF",
              to: "/laporan/gudang-garmen/spk-dtf-belum-po",
              icon: IconFileAlert,
              menuId: 516,
            },
            {
              title: "SPK vs Realisasi vs LHK Cutting",
              to: "/laporan/gudang-garmen/spkv-realisasiv-lhkcutt",
              icon: IconListCheck,
              menuId: 517,
            },
            {
              title: "SPK vs STBJ vs SJ",
              to: "/laporan/gudang-garmen/spk-vs-stbj-vs-sj",
              icon: IconTruckLoading,
              menuId: 518,
            },
            {
              title: "SPK MKB vs PO BPB",
              to: "/laporan/gudang-garmen/spk-mkb-vs-po-bpb",
              icon: IconFileAnalytics,
              menuId: 519,
            },
            {
              title: "SPK vs PO",
              to: "/laporan/gudang-garmen/spk-vs-po",
              icon: IconFileInvoice,
              menuId: 520,
            },
            {
              title: "SPK vs BPB",
              to: "/laporan/gudang-garmen/spk-vs-bpb",
              icon: IconTruckDelivery,
              menuId: 521,
            },
            {
              title: "SPK vs BPB Non PO",
              to: "/laporan/gudang-garmen/spk-vs-bpb-non-po",
              icon: IconTruckDelivery,
              menuId: 522,
            },
            {
              title: "SPK Close STBJ",
              to: "/laporan/gudang-garmen/spk-close-stbj",
              icon: IconCircleCheck,
              menuId: 523,
            },
            {
              title: "Mutasi Produksi with Detail",
              to: "/laporan/gudang-garmen/mutasi-prod-detail",
              icon: IconLayoutGrid,
              menuId: 524,
            },
            {
              title: "Laporan Kekurangan Produksi",
              to: "/laporan/gudang-garmen/kekurangan-produksi",
              icon: IconAlertTriangle,
              menuId: 525,
            },
            {
              title: "Outstanding SPK",
              to: "/laporan/gudang-garmen/lap-outstanding-spk",
              icon: IconClipboardList,
              menuId: 526,
            },
            {
              title: "Browse SPK",
              to: "/laporan/gudang-garmen/browse-spk",
              icon: IconClipboardList,
              menuId: 527,
            },
            {
              title: "Browse MAP",
              to: "/laporan/gudang-garmen/browse-map",
              icon: IconClipboardList,
              menuId: 528,
            },
          ],
        },
        {
          title: "Laporan Produksi Garmen",
          icon: IconActivity,
          menuId: 961,
          subItems: [
            {
              title: "Monitoring Proof",
              to: "/laporan/produksi-garmen/monitoring-proof",
              icon: IconClipboardCheck,
              menuId: 553,
            },
            {
              title: "Monitoring Produksi",
              to: "/laporan/produksi-garmen/monitoring-produksi",
              icon: IconGauge,
              menuId: 554,
            },
            {
              title: "Monitoring Kekurangan Produksi (All Divisi)",
              to: "/laporan/produksi-garmen/monitoring-kurang-prod",
              icon: IconAlertTriangle,
              menuId: 555,
            },
            {
              title: "Monitoring Kekurangan Produksi (Jahit/Line)",
              to: "/laporan/produksi-garmen/monitoring-kurang-prod-jahit",
              icon: IconAlertTriangle,
            },
            {
              title: "Monitoring Kekurangan Produksi v2",
              to: "/laporan/produksi-garmen/monitoring-kurang-prodv2",
              icon: IconAlertTriangle,
              menuId: 556,
            },
            {
              title: "Monitoring Kedatangan Bahan",
              to: "/laporan/produksi-garmen/monitoring-bhn-datang",
              icon: IconTruckDelivery,
              menuId: 557,
            },
            {
              title: "Outstanding Bordir",
              to: "/laporan/produksi-garmen/outstanding-bordir",
              icon: IconAlertTriangle,
              menuId: 558,
            },
            {
              title: "Standar Babaran Proof",
              to: "/laporan/produksi-garmen/std-babaran-proof",
              icon: IconRuler2,
              menuId: 559,
            },
            {
              title: "Study Time Proses Proof Jahit",
              to: "/laporan/produksi-garmen/study-time-proof-jahit",
              icon: IconClockHour4,
              menuId: 560,
            },
            {
              title: "Study Time Proses Proof Cetak",
              to: "/laporan/produksi-garmen/study-time-proof-cetak",
              icon: IconClockHour4,
              menuId: 561,
            },
            {
              title: "Study Time Proses Proof Bordir",
              to: "/laporan/produksi-garmen/study-time-proof-bordir",
              icon: IconClockHour4,
              menuId: 562,
            },
            {
              title: "Monitoring BS",
              to: "/laporan/produksi-garmen/monitoring-bs",
              icon: IconAlertTriangle,
              menuId: 563,
            },
            {
              title: "Stok Produksi by Line",
              to: "/laporan/produksi-garmen/stok-by-line",
              icon: IconLayoutGrid,
              menuId: 564,
            },
            {
              title: "Pemakaian Obat",
              to: "/laporan/produksi-garmen/pemakaian-obat",
              icon: IconFlask,
              menuId: 565,
            },
          ],
        },
        {
          title: "Laporan Penjualan",
          icon: IconChartBar,
          menuId: 965,
          subItems: [
            {
              title: "Penawaran vs SPK",
              to: "/laporan/penjualan/penawaran-vs-spk",
              icon: IconReportAnalytics,
              menuId: 301,
            },
            {
              title: "Realisasi Penawaran",
              to: "/laporan/penjualan/realisasi-penawaran",
              icon: IconReportAnalytics,
            },
            {
              title: "SPK vs STBJ",
              to: "/laporan/penjualan/spk-vs-stbj",
              icon: IconClipboardList,
              menuId: 304,
            },
            {
              title: "SPK vs SJ",
              to: "/laporan/penjualan/spk-vs-sj",
              icon: IconTruckDelivery,
              menuId: 305,
            },
            {
              title: "SO vs SJ vs Invoice",
              to: "/laporan/penjualan/spk-vs-sj-vs-inv",
              icon: IconFileInvoice,
              menuId: 306,
            },
            {
              title: "MAP vs Surat Jalan",
              to: "/laporan/penjualan/map-vs-sj",
              icon: IconTruckDelivery,
              menuId: 307,
            },
            {
              title: "MAP vs SPK",
              to: "/laporan/penjualan/map-vs-spk",
              icon: IconClipboardList,
              menuId: 308,
            },
          ],
        },
        {
          title: "Laporan Marketing",
          icon: IconChartBar,
          menuId: 966,
          subItems: [
            {
              title: "Penawaran vs MAP",
              to: "/laporan/marketing/penawaran-vs-map",
              icon: IconReportAnalytics,
            },
            {
              title: "Target SPK",
              to: "/laporan/marketing/target-spk",
              icon: IconTarget,
              menuId: 312,
            },
            {
              title: "Target vs Realisasi",
              to: "/laporan/marketing/target-vs-realisasi",
              icon: IconTarget,
              menuId: 966,
            },
            {
              title: "Proyeksi vs Realisasi",
              to: "/laporan/marketing/proyeksi-vs-realisasi",
              icon: IconTrendingUp,
              menuId: 1244,
            },
            {
              title: "MAP Belum Terealisasi",
              to: "/laporan/marketing/map-belum-realisasi",
              icon: IconFileAlert,
            },
            {
              title: "SO Belum Closing",
              to: "/laporan/marketing/spk-belum-closing",
              icon: IconClipboardX,
            },
            {
              title: "Realisasi Penjualan",
              to: "/laporan/marketing/realisasi-penjualan",
              icon: IconTrendingUp,
              menuId: 966,
            },
            {
              title: "Rekap MAP",
              to: "/laporan/marketing/rekap-map",
              icon: IconLayoutGrid,
              menuId: 311,
            },
            {
              title: "Rekap Penawaran",
              to: "/laporan/marketing/rekap-penawaran",
              icon: IconReportSearch,
              menuId: 310,
            },
            {
              title: "Revisi Memo SPK",
              to: "/laporan/marketing/revisi-map",
              icon: IconFileDiff,
              menuId: 966,
            },
            {
              title: "Realisasi Pengiriman SPK",
              to: "/laporan/marketing/realisasi-kirim-spk",
              icon: IconTruckDelivery,
              menuId: 302,
            },
            {
              title: "Realisasi Pengiriman Memo",
              to: "/laporan/marketing/realisasi-kirim-memo",
              icon: IconTruckDelivery,
              menuId: 303,
            },
            {
              title: "Proyeksi Bulanan",
              to: "/laporan/marketing/proyeksi-bulanan",
              icon: IconChartLine,
              menuId: 1294,
            },
            {
              title: "Kunjungan Sales",
              to: "/laporan/marketing/kunjungan-sales",
              icon: IconTruckDelivery,
              menuId: 313,
            },
            {
              title: "Target vs Achievement",
              to: "/laporan/marketing/target-vs-achievement",
              icon: IconChartBar,
              menuId: 314,
            },
          ],
        },
        {
          title: "Laporan Piutang",
          icon: IconCreditCard,
          menuId: 968,
          subItems: [
            {
              title: "Detail Piutang",
              to: "/laporan/piutang/detail-piutang",
              icon: IconFileInvoice,
              // Sengaja tanpa menuId, agar mengikuti hak akses parent-nya (968)
            },
            {
              title: "Rekap Piutang",
              to: "/laporan/piutang/rekap-piutang",
              icon: IconFileAnalytics, // Pastikan di-import di menu definition
            },
            {
              title: "Kartu Piutang",
              to: "/laporan/piutang/kartu-piutang",
              icon: IconFileDescription,
            },
            { divider: true },
            {
              title: "Daftar Penerimaan",
              to: "/laporan/piutang/daftar-penerimaan",
              icon: IconCurrencyDollar,
            },
            {
              title: "Cek Gagal Link",
              to: "/laporan/piutang/cek-gagal-link",
              icon: IconLinkOff,
            },
          ],
        },
      ],
    },
    {
      title: "Tools",
      icon: IconTool,
      model: toolsMenu,
      adminOnly: false,
      items: [
        { title: "Master User", to: "/tools/users", icon: IconUsers },
        { title: "Approval", to: "/tools/approval", icon: IconShieldCheck },
        { divider: true },
        {
          title: "Relationship Map",
          to: "/tools/relationship-map",
          icon: IconHierarchy3,
          menuId: 1321,
        },
        {
          title: "Sistem Informasi Bahan",
          to: "/tools/sistem-informasi-bahan",
          icon: IconDatabaseSearch,
          menuId: 1322,
        },
        {
          title: "Kelola PIC Agenda",
          to: "/tools/kelola-pic-agenda",
          icon: IconCalendarCog,
          menuId: 124,
        },
      ],
    },
  ];
};
